### PR TITLE
fixing freazseal

### PR DESCRIPTION
**Pull request by ehsanhrz**
my first little commit 😄

### CODE REVIEW

**Comment by conartist6** [comment]
I know it's a small commit, but let's get it right! There's no more need for a `result` variable.

**Comment by ehsanhrz** [comment]
now i'm trying to make the pull request

**Comment by ehsanhrz** [comment]
done

**Comment by conartist6** [comment]
I changed the commit verb from "fix" to "cleanup" since there was no bug present. Otherwise great; thanks!

**Pull request merged**
